### ISSUE TITLE
Syntax error MEDIA_ESL_AUTHENTICATION_ERROR is not defined

### ISSUE THREAD

**Issue by andrewfr** [mconf/bbb-transcription-controller#1]
I am setting up bbb-transcription-controller. I am using nodeenv. The docker container is running. When I execute
node app.js

I get

2023-01-11T17:59:00.150Z - error: [transcript-manager] FSESL connection authentication error
/home/andrew/bbb/projects/bbb-transcription-controller/lib/esl-wrapper.js:149
        this.error = this._normalizeError(MEDIA_ESL_AUTHENTICATION_ERROR, error.message)
                                          ^

ReferenceError: MEDIA_ESL_AUTHENTICATION_ERROR is not defined

If a password is involved where should I set it?

**Comment by andrewfr** [comment]
I have set the Freeswitch password. The app is now running. I am running the Vosk container locally. In default.yaml, I have used wss://127.0.0.1:2007/voskEN as a URL. As moderator, I turn captions on. In my webcam window, I click on CC. I get the following

2023-01-14T18:12:51.233Z - info: [transcript-manager] FS: Start talking 8235c5bd-fbf7-4e53-b39a-283fe6ce155b userId: w_7spd1vqgq7b5
2023-01-14T18:12:51.234Z - warn: [transcript-manager] No provider set, not transcribing
2023-01-14T18:12:52.594Z - info: [transcript-manager] FS: Stop Talking 8235c5bd-fbf7-4e53-b39a-283fe6ce155b userId: w_7spd1vqgq7b5

What does it mean? How do I fix this?

**Comment by lfzawacki** [comment]
Hey Andrew, it seems that the transcription controller hasn't received a message from the HTML5 client informing it of the speech-to-text locale to use. If you're using the correct BBB branch and latest akka-bbb-apps and bbb-web compiled from it the HTML5 client should emit [this message](https://github.com/mconf/bbb-transcription-controller/blob/main/app.js#L31)  whenever you select a language for transcription.

Also, not related to this problem you're seeing, but I'm not sure if using an ip address and the wss:// protocol for websockets will work, since it won't be able to find the correct TLS certificate for an ip address and won't be able to setup the connection. I'd recommend you use your hostname instead of 127.0.0.1 and setup an NGINX reverse proxy as described in the readme.

Hope this helps.

**Comment by lfzawacki** [comment]
> I am new to BBB. I initially tested with BBB 2.5 because it was easier to set up the demo mode. I'll shift to BBB 2.6 and set up accounts. Is the installer grabbing the most up to date versions?
> 

Ok, so that's the problem. This project uses a modified version of BBB that includes this new transcription functionality. It's not currently merged into the project, you would have to build some components from this pull request here https://github.com/bigbluebutton/bigbluebutton/pull/16442

Developing for BBB is quite complex, there's extensive documentation [here](https://docs.bigbluebutton.org/2.6/dev.html). You should start from a 2.6 server and build your own bigbluebutton-web, bbb-akka-apps and bigbluebutton-html5. This should be enough to make this project work.

> I hardly use ngnix. I don't know where to put that fragment. Do I create a voskEN.conf file? Do I just cut-and-paste that fragment in ngnix.conf? I have been reading up on setting up reverse proxy.

The fragment can be placed inside the folder `/usr/share/bigbluebutton/nginx/` . The files here will be auto loaded by Bigbluebutton's default nginx config file.

**Comment by andrewfr** [comment]
Thanks for the answers!
